apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets-system

resources:
  - ../upstream/controller.yaml
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/version: "0.28.0"
    includeSelectors: false

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/priorityClassName
        value: system-cluster-critical
  - target:
      kind: "(Deployment|StatefulSet)"
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 2
