apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - poddisruptionbudget.yaml

labels:
  - pairs:
      app.kubernetes.io/name: sealed-secrets
      app.kubernetes.io/instance: sealed-secrets
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: sealed-secrets-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 64Mi
