apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets-system
spec:
  minAvailable: 0
  selector: {}
  unhealthyPodEvictionPolicy: IfHealthyBudget
